# Generated by Django 3.2.18 on 2023-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer1',
        ),
        migrations.AddField(
            model_name='answer',
            name='context',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
