# Generated by Django 3.2.18 on 2023-05-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0002_auto_20230505_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('mbti', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('mind', models.TextField()),
            ],
        ),
    ]
