# Generated by Django 3.2.18 on 2023-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0004_auto_20230510_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti',
            name='id',
        ),
        migrations.AddField(
            model_name='mbti',
            name='mbti',
            field=models.TextField(default=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
