# Generated by Django 3.2.18 on 2023-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0005_auto_20230510_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mind',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
