# Generated by Django 3.2.18 on 2023-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0007_auto_20230510_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='type',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
