# Generated by Django 3.2.18 on 2023-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0008_auto_20230510_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti',
            name='id',
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mind',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mbti',
            name='type',
            field=models.TextField(),
        ),
    ]
