# Generated by Django 3.2.18 on 2023-05-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0011_remove_mbti_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
