# Generated by Django 3.2.18 on 2023-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0013_alter_mbti_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='id',
            field=models.TextField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mind',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
