# Generated by Django 3.2.18 on 2023-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0014_auto_20230510_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
