# Generated by Django 3.2.18 on 2023-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0015_auto_20230510_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='context',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.TextField(default=''),
        ),
    ]
