# Generated by Django 3.2.18 on 2023-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0016_auto_20230510_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti',
            name='mbti',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
