# Generated by Django 3.2.18 on 2023-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtiapp', '0017_auto_20230510_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
